version: "3"

services: 
   app:
    container_name: app
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./src/:/app
    ports:
      - 8000:8000
    links:
      - redis
      - celery_worker
    restart: always
  
   redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

   celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - ./src/:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis://redis:6379/0
    links:
      - redis
    depends_on:
      - redis

   flower:
      container_name: flower
      build: .
      command: celery -A worker.celery_app flower --port=5555
      
      ports:
        - 5555:5555
      volumes:
        - ./src/:/app
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
      depends_on:
        - app
        - redis
        - celery_worker

